name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build-job:
    name: Build Static Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Static Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-development"

  deploy-job:
    needs: build-job
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment: development
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Artifacts on GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-development"
          token: ${{ secrets.GITHUB_TOKEN }}
